# -*- coding: utf-8 -*-
# Stratified data split script

import os
import shutil
from sklearn.model_selection import train_test_split
from config import RAW_DATA_DIR, TRAIN_DATA_DIR, VAL_DATA_DIR, TRAIN_VAL_SPLIT

def get_class_distribution(data_dir):
    """Count samples per class"""
    distribution = {}
    exclude_dirs = {'train', 'val'}
    for class_name in os.listdir(data_dir):
        class_path = os.path.join(data_dir, class_name)
        if os.path.isdir(class_path) and class_name not in exclude_dirs:
            images = [f for f in os.listdir(class_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
            distribution[class_name] = len(images)
    return distribution

def split_dataset():
    print("=" * 40)
    print("Stratified Data Split")
    print("=" * 40)
    
    # Check raw data directory
    if not os.path.exists(RAW_DATA_DIR):
        print(f"Error: Raw data directory not found: {RAW_DATA_DIR}")
        return
    
    # Exclude train/val directories (generated by previous runs)
    exclude_dirs = {'train', 'val'}
    classes = [d for d in os.listdir(RAW_DATA_DIR) 
               if os.path.isdir(os.path.join(RAW_DATA_DIR, d)) and d not in exclude_dirs]
    if not classes:
        print(f"Error: No class subdirectories found")
        return
    
    print(f"Found {len(classes)} classes: {classes}")
    
    # Count original distribution
    print("\nOriginal data distribution:")
    orig_dist = get_class_distribution(RAW_DATA_DIR)
    for cls, cnt in orig_dist.items():
        print(f"  {cls}: {cnt}")
    
    # Create target directories
    for split_dir in [TRAIN_DATA_DIR, VAL_DATA_DIR]:
        for cls in classes:
            os.makedirs(os.path.join(split_dir, cls), exist_ok=True)
    
    # Stratified split: split each class independently
    for cls in classes:
        cls_dir = os.path.join(RAW_DATA_DIR, cls)
        images = [f for f in os.listdir(cls_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
        
        train_imgs, val_imgs = train_test_split(
            images, 
            train_size=TRAIN_VAL_SPLIT, 
            random_state=42, 
            shuffle=True
        )
        
        # Copy to train
        for img in train_imgs:
            src = os.path.join(cls_dir, img)
            dst = os.path.join(TRAIN_DATA_DIR, cls, img)
            shutil.copy2(src, dst)
        
        # Copy to val
        for img in val_imgs:
            src = os.path.join(cls_dir, img)
            dst = os.path.join(VAL_DATA_DIR, cls, img)
            shutil.copy2(src, dst)
        
        print(f"{cls}: {len(train_imgs)} train, {len(val_imgs)} val")
    
    # Verify split results
    print("\nSplit distribution:")
    print("Train:")
    train_dist = get_class_distribution(TRAIN_DATA_DIR)
    for cls, cnt in train_dist.items():
        ratio = cnt / orig_dist[cls] if orig_dist[cls] > 0 else 0
        print(f"  {cls}: {cnt} ({ratio:.1%})")
    
    print("Val:")
    val_dist = get_class_distribution(VAL_DATA_DIR)
    for cls, cnt in val_dist.items():
        ratio = cnt / orig_dist[cls] if orig_dist[cls] > 0 else 0
        print(f"  {cls}: {cnt} ({ratio:.1%})")
    
    print("\nData split completed!")

if __name__ == '__main__':
    split_dataset()
